config/routes.rb
Rails.application.routes.draw do
  resources :customers, only: [:new, :create, :show] do
    resources :compensations, only: [:create, :destroy]
  end
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'customers#new', as: :signup
  get 'login', to: 'sessions#new', as: :login
  get 'logout', to: 'sessions#destroy', as: :logout

  root to: 'sessions#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/compensation.rb
class Compensation < ApplicationRecord
  include LawyersHelper

  belongs_to :customer
  belongs_to :lawyer

  validates_presence_of :title
  validates_presence_of :customer, :lawyer

  before_validation(on: :create) do
    self.lawyer = match_lawyer(self.customer)
  end
end

app/models/customer.rb
class Customer < User
  has_many :compensations
end

app/models/lawyer.rb
class Lawyer < User
  has_many :compensations
  has_many :clients, through: :compensations, source: :customer
end

app/models/state.rb
class State < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :state
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def require_login
    unless valid_session?
      redirect_to login_path
    else
      redirect_to customer_path(user) unless user_can?
      user
    end
  end

  def dispatch_logged_users
    if valid_session?
      redirect_to customer_path(user)
    end
  end

  def user
    get_logged_user
  end

  private

  def user_can?
    user_id = get_logged_user.id
    request&.params[:customer_id]&.to_i == user_id || request&.params[:id]&.to_i == user_id
  end

  def get_logged_user
    @current_customer ||= Customer.find_by(id: session_user_id)
  end

  def valid_session?
    session_user_id.present?
  end

  def session_user_id
    session[:user_id]
  end
end

app/controllers/compensations_controller.rb
class CompensationsController < ApplicationController
  before_action :require_login
  before_action :set_customer
  before_action :set_compensation, only: :destroy

  def create
    @compensation = @customer.compensations.new(compensation_params)
  
    if @compensation.save!
      redirect_to customer_path(@customer.id)
    else
      redirect_to customer_path(@customer.id)
    end
  end

  def destroy
    @compensation.destroy   
    redirect_to customer_path(@customer.id)
  end

  private

  def set_customer
    @customer = Customer.find_by(id: params[:customer_id])
  end

  def set_compensation
    @compensation = @customer.compensations.find_by(id: params[:id])
  end

  def compensation_params
    params.require(:compensation).permit(:title)
  end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :require_login, only: [:show]
  before_action :set_customer, only: [:show]

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      session[:user_id] = @customer.id
      render :show, status: :created, location: @customer
    else
      redirect_to signup_path
    end
  end

  def show
  end

  private

  def set_customer
    @customer = Customer.find_by(id: params[:id])
  end

  def customer_params
    params.require(:customer).permit(:name, :password, :password_confirmation, :email, :state_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :dispatch_logged_users, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.authenticate(params[:user][:password])
      session[:user_id] = @user.id
      redirect_to customer_path(@user)
    else
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lawyers_helper.rb
module LawyersHelper
  def match_lawyer(customer)
    return current_lawyer(customer) if has_lawyer?(customer)

    ids = Lawyer.where(state: customer.state).pluck(:id)

    Lawyer.find_by(id: ids.sample)
  end

  private

  def current_lawyer(customer)
    customer.compensations&.first&.lawyer
  end

  def has_lawyer?(customer)
    customer.compensations.count > 0
  end
end

app/views/compensations/_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="newCompensationModal" tabindex="-1" role="dialog" aria-labelledby="newCompensationModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newCompensationModalLabel">Crie um novo pedido de indenização</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= form_for(Compensation.new, url: customer_compensations_path(@customer.id), method: :post) do |form| %>
      <div class="modal-body">
          <div class="input-group">
            <%= form.text_field :title, class: 'form-control', placeholder: 'Descrição', required: true %>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn button--secondary" data-dismiss="modal">Cancelar</button>
        <button type="submit" class="btn button--primary">Salvar</button>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/customers/_form.html.erb
<%= form_with(model: customer, local: true) do |form| %>
  <div class="form-label-group">
    <%= form.text_field :name, id: 'nameInput', class: 'form-control', required: true %>
    <label for="nameInput">Nome</label>
  </div>

  <div class="form-label-group">
    <%= form.text_field :email, id: 'emailInput', class: 'form-control input_email', required: true %>
    <label for="emailInput">Email</label>
  </div>

  <div class="form-label-group">
    <%= form.collection_select :state_id, State.order(:name), :id, :name, {}, { class: 'form-control' } %>
  </div>

  <div class="form-label-group">
    <%= form.password_field :password, id: 'passwordInput', class: 'form-control input_pass', required: true %>
    <label for="passwordInput">Senha</label>
  </div>

  <div class="form-label-group">
    <%= form.password_field :password, id: 'passwordConfirmationInput', class: 'form-control input_pass', required: true %>
    <label for="passwordConfirmationInput">Confirmação de senha</label>
  </div>

  <button class="btn btn-lg button--primary btn-block text-uppercase" type="submit">Criar conta</button>
  <div class="mt-4">
    <div class="d-flex justify-content-center links">
      Já possui conta? <a href="/login" class="ml-2">Entrar</a>
    </div>
  </div>
<% end %>

app/views/customers/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
      <div class="card card-signin my-5">
        <div class="card-body">
          <h5 class="card-title text-center">Criar conta</h5>
          <%= render 'form', customer: @customer %>    
        </div>
      </div>
    </div>
  </div>
</div>

app/views/customers/show.html.erb
<div class="card text-center">
  <div class="card-body">
    <h5 class="card-title">Oi <%= @customer.name %>, tudo bem?</h5>
    <% if @customer.compensations.present? %>
      <p class="card-text">Você possui um total de <%= @customer.compensations.count %> pedidos de indenização, como mostra abaixo:</p>

      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Descrição</th>
            <th scope="col">Estado</th>
            <th scope="col">Advogado</th>
            <th scope="col">Status</th>
            <th scope="col">Deletar?</th>
          </tr>
        </thead>
        <% @customer.compensations.each do |compensation| %>
        <tbody>
          <tr>
            <th scope="row"><%= compensation.id %></th>
            <td><%= compensation.title %></td>
            <td><%= @customer.state.name %></td>
            <td><%= compensation.lawyer.name %></td>
            <td>Em andamento...</td>
            <td>
              <%= link_to(
                    image_tag(
                      'https://ionicons.com/ionicons/svg/ios-trash.svg', 
                      size: '25x25'
                    ), 
                    customer_compensation_path(compensation.customer.id, compensation.id), 
                    method: :delete, 
                    data: { confirm: 'Realmente deseja deletar?' }) %>
            </td>
          </tr>
        </tbody>
        <% end %>
      </table>
      <button type="button" class="btn button--primary" data-toggle="modal" data-target="#newCompensationModal">Abrir novo pedido</button>
    <% else %>
      <p class="card-text">Você ainda não possui nenhum pedido de indenização</p>
      <button type="button" class="btn button--primary" data-toggle="modal" data-target="#newCompensationModal">Criar pedido</button>
    <% end %>
  </div>
</div>

<%= render 'compensations/modal' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resolvvi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>

    <br>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light bg-white">
  <a class="navbar-brand" href="/">
    <img class="navbar-logo" src="https://uploads-ssl.webflow.com/5b7c0ffd36ef667b08a4a684/5bc76f0d3d3815109b416333_cor.svg">
  </a>
  <% if session[:user_id] %>
  <form action="/logout" class="form-inline">
    <button class="btn button--secondary" type="submit">Logout</button>
  </form>
  <% end %>
</nav>